/** ISO 3166-1 alpha-2 countries grouped for Jev Choice questions (max 255 options). */
export const REGIONS = {
  africa: {
    label: "Africa",
    countries: {
      DZ: "Algeria",
      AO: "Angola",
      BJ: "Benin",
      BW: "Botswana",
      BF: "Burkina Faso",
      BI: "Burundi",
      CV: "Cabo Verde",
      CM: "Cameroon",
      CF: "Central African Republic",
      TD: "Chad",
      KM: "Comoros",
      CG: "Congo",
      CD: "Democratic Republic of the Congo",
      CI: "Côte d'Ivoire",
      DJ: "Djibouti",
      EG: "Egypt",
      GQ: "Equatorial Guinea",
      ER: "Eritrea",
      SZ: "Eswatini",
      ET: "Ethiopia",
      GA: "Gabon",
      GM: "Gambia",
      GH: "Ghana",
      GN: "Guinea",
      GW: "Guinea-Bissau",
      KE: "Kenya",
      LS: "Lesotho",
      LR: "Liberia",
      LY: "Libya",
      MG: "Madagascar",
      MW: "Malawi",
      ML: "Mali",
      MR: "Mauritania",
      MU: "Mauritius",
      MA: "Morocco",
      MZ: "Mozambique",
      NA: "Namibia",
      NE: "Niger",
      NG: "Nigeria",
      RW: "Rwanda",
      ST: "São Tomé and Príncipe",
      SN: "Senegal",
      SC: "Seychelles",
      SL: "Sierra Leone",
      SO: "Somalia",
      ZA: "South Africa",
      SS: "South Sudan",
      SD: "Sudan",
      TZ: "Tanzania",
      TG: "Togo",
      TN: "Tunisia",
      UG: "Uganda",
      ZM: "Zambia",
      ZW: "Zimbabwe",
    },
  },
  americas: {
    label: "Americas",
    countries: {
      AG: "Antigua and Barbuda",
      AR: "Argentina",
      BS: "Bahamas",
      BB: "Barbados",
      BZ: "Belize",
      BO: "Bolivia",
      BR: "Brazil",
      CA: "Canada",
      CL: "Chile",
      CO: "Colombia",
      CR: "Costa Rica",
      CU: "Cuba",
      DM: "Dominica",
      DO: "Dominican Republic",
      EC: "Ecuador",
      SV: "El Salvador",
      GD: "Grenada",
      GT: "Guatemala",
      GY: "Guyana",
      HT: "Haiti",
      HN: "Honduras",
      JM: "Jamaica",
      MX: "Mexico",
      NI: "Nicaragua",
      PA: "Panama",
      PY: "Paraguay",
      PE: "Peru",
      KN: "Saint Kitts and Nevis",
      LC: "Saint Lucia",
      VC: "Saint Vincent and the Grenadines",
      SR: "Suriname",
      TT: "Trinidad and Tobago",
      US: "United States",
      UY: "Uruguay",
      VE: "Venezuela",
    },
  },
  asia: {
    label: "Asia",
    countries: {
      AF: "Afghanistan",
      AM: "Armenia",
      AZ: "Azerbaijan",
      BH: "Bahrain",
      BD: "Bangladesh",
      BT: "Bhutan",
      BN: "Brunei",
      KH: "Cambodia",
      CN: "China",
      CY: "Cyprus",
      GE: "Georgia",
      IN: "India",
      ID: "Indonesia",
      IR: "Iran",
      IQ: "Iraq",
      IL: "Israel",
      JP: "Japan",
      JO: "Jordan",
      KZ: "Kazakhstan",
      KW: "Kuwait",
      KG: "Kyrgyzstan",
      LA: "Laos",
      LB: "Lebanon",
      MY: "Malaysia",
      MV: "Maldives",
      MN: "Mongolia",
      MM: "Myanmar",
      NP: "Nepal",
      KP: "North Korea",
      OM: "Oman",
      PK: "Pakistan",
      PS: "Palestine",
      PH: "Philippines",
      QA: "Qatar",
      SA: "Saudi Arabia",
      SG: "Singapore",
      KR: "South Korea",
      LK: "Sri Lanka",
      SY: "Syria",
      TW: "Taiwan",
      TJ: "Tajikistan",
      TH: "Thailand",
      TL: "Timor-Leste",
      TR: "Turkey",
      TM: "Turkmenistan",
      AE: "United Arab Emirates",
      UZ: "Uzbekistan",
      VN: "Vietnam",
      YE: "Yemen",
      HK: "Hong Kong",
    },
  },
  europe: {
    label: "Europe",
    countries: {
      AL: "Albania",
      AD: "Andorra",
      AT: "Austria",
      BY: "Belarus",
      BE: "Belgium",
      BA: "Bosnia and Herzegovina",
      BG: "Bulgaria",
      HR: "Croatia",
      CZ: "Czechia",
      DK: "Denmark",
      EE: "Estonia",
      FI: "Finland",
      FR: "France",
      DE: "Germany",
      GR: "Greece",
      HU: "Hungary",
      IS: "Iceland",
      IE: "Ireland",
      IT: "Italy",
      XK: "Kosovo",
      LV: "Latvia",
      LI: "Liechtenstein",
      LT: "Lithuania",
      LU: "Luxembourg",
      MT: "Malta",
      MD: "Moldova",
      MC: "Monaco",
      ME: "Montenegro",
      NL: "Netherlands",
      MK: "North Macedonia",
      NO: "Norway",
      PL: "Poland",
      PT: "Portugal",
      RO: "Romania",
      RU: "Russia",
      SM: "San Marino",
      RS: "Serbia",
      SK: "Slovakia",
      SI: "Slovenia",
      ES: "Spain",
      SE: "Sweden",
      CH: "Switzerland",
      UA: "Ukraine",
      GB: "United Kingdom",
      VA: "Vatican City",
    },
  },
  oceania: {
    label: "Oceania",
    countries: {
      AU: "Australia",
      FJ: "Fiji",
      KI: "Kiribati",
      MH: "Marshall Islands",
      FM: "Micronesia",
      NR: "Nauru",
      NZ: "New Zealand",
      PW: "Palau",
      PG: "Papua New Guinea",
      WS: "Samoa",
      SB: "Solomon Islands",
      TO: "Tonga",
      TV: "Tuvalu",
      VU: "Vanuatu",
    },
  },
};

export const REGION_KEYS = /** @type {const} */ (["africa", "americas", "asia", "europe", "oceania"]);

/** @type {Record<string, string>} */
export const COUNTRY_NAMES = {
  DZ: "Algeria",
  AO: "Angola",
  BJ: "Benin",
  BW: "Botswana",
  BF: "Burkina Faso",
  BI: "Burundi",
  CV: "Cabo Verde",
  CM: "Cameroon",
  CF: "Central African Republic",
  TD: "Chad",
  KM: "Comoros",
  CG: "Congo",
  CD: "Democratic Republic of the Congo",
  CI: "Côte d'Ivoire",
  DJ: "Djibouti",
  EG: "Egypt",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  SZ: "Eswatini",
  ET: "Ethiopia",
  GA: "Gabon",
  GM: "Gambia",
  GH: "Ghana",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  KE: "Kenya",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libya",
  MG: "Madagascar",
  MW: "Malawi",
  ML: "Mali",
  MR: "Mauritania",
  MU: "Mauritius",
  MA: "Morocco",
  MZ: "Mozambique",
  NA: "Namibia",
  NE: "Niger",
  NG: "Nigeria",
  RW: "Rwanda",
  ST: "São Tomé and Príncipe",
  SN: "Senegal",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SO: "Somalia",
  ZA: "South Africa",
  SS: "South Sudan",
  SD: "Sudan",
  TZ: "Tanzania",
  TG: "Togo",
  TN: "Tunisia",
  UG: "Uganda",
  ZM: "Zambia",
  ZW: "Zimbabwe",
  AG: "Antigua and Barbuda",
  AR: "Argentina",
  BS: "Bahamas",
  BB: "Barbados",
  BZ: "Belize",
  BO: "Bolivia",
  BR: "Brazil",
  CA: "Canada",
  CL: "Chile",
  CO: "Colombia",
  CR: "Costa Rica",
  CU: "Cuba",
  DM: "Dominica",
  DO: "Dominican Republic",
  EC: "Ecuador",
  SV: "El Salvador",
  GD: "Grenada",
  GT: "Guatemala",
  GY: "Guyana",
  HT: "Haiti",
  HN: "Honduras",
  JM: "Jamaica",
  MX: "Mexico",
  NI: "Nicaragua",
  PA: "Panama",
  PY: "Paraguay",
  PE: "Peru",
  KN: "Saint Kitts and Nevis",
  LC: "Saint Lucia",
  VC: "Saint Vincent and the Grenadines",
  SR: "Suriname",
  TT: "Trinidad and Tobago",
  US: "United States",
  UY: "Uruguay",
  VE: "Venezuela",
  AF: "Afghanistan",
  AM: "Armenia",
  AZ: "Azerbaijan",
  BH: "Bahrain",
  BD: "Bangladesh",
  BT: "Bhutan",
  BN: "Brunei",
  KH: "Cambodia",
  CN: "China",
  CY: "Cyprus",
  GE: "Georgia",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran",
  IQ: "Iraq",
  IL: "Israel",
  JP: "Japan",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Laos",
  LB: "Lebanon",
  MY: "Malaysia",
  MV: "Maldives",
  MN: "Mongolia",
  MM: "Myanmar",
  NP: "Nepal",
  KP: "North Korea",
  OM: "Oman",
  PK: "Pakistan",
  PS: "Palestine",
  PH: "Philippines",
  QA: "Qatar",
  SA: "Saudi Arabia",
  SG: "Singapore",
  KR: "South Korea",
  LK: "Sri Lanka",
  SY: "Syria",
  TW: "Taiwan",
  TJ: "Tajikistan",
  TH: "Thailand",
  TL: "Timor-Leste",
  TR: "Turkey",
  TM: "Turkmenistan",
  AE: "United Arab Emirates",
  UZ: "Uzbekistan",
  VN: "Vietnam",
  YE: "Yemen",
  HK: "Hong Kong",
  AL: "Albania",
  AD: "Andorra",
  AT: "Austria",
  BY: "Belarus",
  BE: "Belgium",
  BA: "Bosnia and Herzegovina",
  BG: "Bulgaria",
  HR: "Croatia",
  CZ: "Czechia",
  DK: "Denmark",
  EE: "Estonia",
  FI: "Finland",
  FR: "France",
  DE: "Germany",
  GR: "Greece",
  HU: "Hungary",
  IS: "Iceland",
  IE: "Ireland",
  IT: "Italy",
  XK: "Kosovo",
  LV: "Latvia",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MT: "Malta",
  MD: "Moldova",
  MC: "Monaco",
  ME: "Montenegro",
  NL: "Netherlands",
  MK: "North Macedonia",
  NO: "Norway",
  PL: "Poland",
  PT: "Portugal",
  RO: "Romania",
  RU: "Russia",
  SM: "San Marino",
  RS: "Serbia",
  SK: "Slovakia",
  SI: "Slovenia",
  ES: "Spain",
  SE: "Sweden",
  CH: "Switzerland",
  UA: "Ukraine",
  GB: "United Kingdom",
  VA: "Vatican City",
  AU: "Australia",
  FJ: "Fiji",
  KI: "Kiribati",
  MH: "Marshall Islands",
  FM: "Micronesia",
  NR: "Nauru",
  NZ: "New Zealand",
  PW: "Palau",
  PG: "Papua New Guinea",
  WS: "Samoa",
  SB: "Solomon Islands",
  TO: "Tonga",
  TV: "Tuvalu",
  VU: "Vanuatu",
};

export function countryName(iso) {
  if (!iso) return null;
  const key = String(iso).toUpperCase();
  return COUNTRY_NAMES[key] || null;
}

export function regionCriteria() {
  return {
    africa: "The article is mainly about a country in Africa.",
    americas: "The article is mainly about a country in North or South America or the Caribbean.",
    asia: "The article is mainly about a country in Asia, the Middle East, or the Caucasus.",
    europe: "The article is mainly about a country in Europe, including Russia, Ukraine, and Turkey when the story is European.",
    oceania: "The article is mainly about a country in Australia, New Zealand, or the Pacific islands.",
    none: "No single country is the subject, or the geography is only a dateline, byline, or reporter location.",
  };
}

export function countriesInRegion(region) {
  const block = REGIONS[region];
  if (!block) return { none: "No single country in this region is the subject." };
  return { ...block.countries, none: "No single country in this region is the subject." };
}

